services:
  - type: web
    name: rofellods-mtg-search
    env: static
    buildCommand: echo No build required
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
