services:
  - type: web
    name: rofellods-mtg-search
    env: static
    buildCommand: ./build.sh
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
